"""Generate the in-game verification checklist from `@verify-ingame` markers.

The KB accumulates claims that can only be confirmed while logged into the game
("confirm in-game", "verify %s at the obelisk", ...). Left as free-text TODOs
scattered across ~40 files they rot silently — because resolving them needs you
in-game, but the KB workflow is desk-side, so they're never surfaced at the right
moment. Fix: tag the claim's line with the literal marker `@verify-ingame`; this
tool greps every marker across knowledge/ and rewrites the generated block in
`knowledge/_meta/verify-in-game.md` — one checklist, grouped by file, that
/sync-characters surfaces when you're actually logged in.

Source of truth is the tag at the claim (like candidates.json <- activities/*.md,
never hand-edit the generated output). Resolve an item by confirming it in-game,
then EDIT the source line: drop the marker, update the claim + confidence + date.
It disappears from the list on the next run.

    uv run python -m wowkb.gen_verify            # rewrite the generated block
    uv run python -m wowkb.gen_verify --check     # exit 1 if the block is stale (CI)
    uv run python -m wowkb.gen_verify --print     # print the block to stdout, don't write

A `@verify-ingame` written inside `backticks` is treated as prose (docs referring
to the convention) and ignored — only a live, bare marker counts as an open item.

KNOWN + DELIBERATE: `knowledge/addon-dev/` is effectively invisible to this tool.
64 of its 68 markers are backticked, so it contributes ~zero rows. That subtree is
firewalled from the game KB by its own README §0 (different sources, different
tiers, different reader), and its questions are *engineering* tests — "does the
sandbox expose `require`?" — not things you resolve while logged in doing content.
They live in their own registry, `projects/addon-lab/questions.json`, keyed by a
stable id and run by the ClientLab addon. Do NOT "fix" this by un-backticking those
markers or by teaching `_strip_code` about the subtree: it would drown this
checklist. Decision recorded 2026-07-23 (W1); see `knowledge/addon-dev/README.md` §6.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
KB = REPO / "knowledge"
HOME = KB / "_meta" / "verify-in-game.md"

MARKER = "@verify-ingame"
BEGIN = "<!-- gen_verify:begin -->"
END = "<!-- gen_verify:end -->"

_CODE_SPAN = re.compile(r"`[^`]*`")


def _strip_code(line: str) -> str:
    """Drop inline `code spans` so a backticked marker mention doesn't self-match."""
    return _CODE_SPAN.sub("", line)


def _clean(line: str, limit: int = 140) -> str:
    """Reduce a tagged source line to a short, bare claim for the checklist.

    A single physical line is all we have, so wrapped prose yields a fragment and
    table rows are long — the `path:line` anchor on each item is the real handle;
    this just makes the row scannable. Long text is truncated.
    """
    s = line.strip()
    s = re.sub(r"^>+\s*", "", s)               # blockquote marker
    s = re.sub(r"^#+\s*", "", s)               # heading marker
    s = re.sub(r"^([-*]|\d+[.)])\s+", "", s)   # list bullet
    s = re.sub(r"^\[[ xX~]\]\s*", "", s)       # checkbox
    s = re.sub(r"^\|\s*", "", s)               # leading table-cell pipe
    s = s.replace(MARKER, "")
    s = re.sub(r"\s+", " ", s).strip()
    s = s.strip(" —-–:|")
    if len(s) > limit:
        s = s[: limit - 1].rstrip() + "…"
    return s


def find_items() -> list[tuple[str, int, str]]:
    """(repo-relative path, 1-based line, cleaned text) for every live marker."""
    items: list[tuple[str, int, str]] = []
    for path in sorted(KB.rglob("*.md")):
        if path == HOME:
            continue
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError:
            continue
        for i, line in enumerate(lines, 1):
            if MARKER in _strip_code(line):
                rel = path.relative_to(REPO).as_posix()
                items.append((rel, i, _clean(line)))
    return items


def render_block(items: list[tuple[str, int, str]]) -> str:
    out = [
        BEGIN,
        f"_Generated by `wowkb.gen_verify` — do not hand-edit this block. "
        f"{len(items)} open item(s)._",
        "",
    ]
    if not items:
        out.append("_No open in-game verifications. \U0001F389_")
    else:
        by_file: dict[str, list[tuple[int, str]]] = {}
        for rel, ln, text in items:
            by_file.setdefault(rel, []).append((ln, text))
        for rel in sorted(by_file):
            out.append(f"### `{rel}`")
            for ln, text in by_file[rel]:
                out.append(f"- [ ] {text} — `{rel}:{ln}`")
            out.append("")
    out.append(END)
    return "\n".join(out).rstrip() + "\n"


def splice(doc: str, block: str) -> str:
    """Replace the region between the sentinels; append it if not present yet."""
    if BEGIN in doc and END in doc:
        pre = doc[: doc.index(BEGIN)]
        post = doc[doc.index(END) + len(END):]
        return pre + block.rstrip("\n") + post
    sep = "" if doc.endswith("\n") else "\n"
    return doc + sep + "\n" + block


_SCAFFOLD = f"""---
title: In-Game Verification Checklist
patch: 12.0.7
confidence: high
---

# In-Game Verification Checklist

Open KB claims that need confirming **while logged into the game**. The list
below is generated from `{MARKER}` markers in the KB — do not hand-edit it; see
`wowkb.gen_verify`.

{BEGIN}
{END}
"""


def main(argv=None) -> int:
    p = argparse.ArgumentParser(
        prog="wowkb.gen_verify", description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--check", action="store_true",
                   help="exit 1 if the generated block is out of date (CI guard)")
    p.add_argument("--print", dest="to_stdout", action="store_true",
                   help="print the block to stdout instead of writing the file")
    args = p.parse_args(argv)

    items = find_items()
    block = render_block(items)

    if args.to_stdout:
        sys.stdout.write(block)
        return 0

    doc = HOME.read_text(encoding="utf-8") if HOME.exists() else _SCAFFOLD
    updated = splice(doc, block)

    if args.check:
        if not HOME.exists() or HOME.read_text(encoding="utf-8") != updated:
            print(f"OUT OF DATE: {HOME.relative_to(REPO)} — "
                  f"re-run `python -m wowkb.gen_verify`")
            return 1
        print(f"up to date ({len(items)} open items)")
        return 0

    HOME.write_text(updated, encoding="utf-8")
    print(f"wrote {HOME.relative_to(REPO)} — {len(items)} open in-game items")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
