"""Per-spec ability inventory from Blizzard game data — the union model.

Phase 0 of the layout-v2 §6 re-filing pipeline (see
projects/keybinder/data/layout-v2-proposal.md). Builds, for every playable spec,
the authoritative list of abilities the spec can PRESS — every talent-granted
active plus the shared class kit the talent tree omits — joined to objective
cooldown durations, the Cooldown Manager's own Essential/Utility signal, and the
current BucketBinds seed.

Why the union (and why the first cut was wrong): the original tool built its
inventory from `CooldownSetSpell` — the Cooldown Manager's *tracking config*.
That is incomplete by design: it lists what's worth showing on a cooldown
tracker, which systematically omits no-cooldown utility. Five real Demonology
abilities were absent that way (Create Healthstone, Demonic Circle, Burning Rush,
Drain Life, Summon Felguard), four of which the seed already binds. So the
inventory is now a UNION of three sources:

  1. `all-talents.tsv`  — every talent-granted active (node_type != PASSIVE),
                          keyed by spec_id. Tier 1 (Blizzard Game Data API,
                          cross-checked vs wago Trait*). Generated by wowkb.talents.
  2. `SkillLineAbility`  — the shared class kit the tree omits (Create Healthstone,
                          Fear, Drain Life, Eye of Kilrogg …). Filtered to the
                          class skill line (ClassMask == 1<<(classID-1) OR 0, the
                          latter meaning "all specs of the class"), dropping dead
                          Legion artifact rows (AcquireMethod == 3) and passives.
  3. `CooldownSetSpell`  — kept only as ANNOTATION now (Essential/Utility category +
                          Blizzard's OrderIndex). Spells present ONLY here land as
                          origin `cdm-only` so nothing the old tool surfaced is lost
                          (e.g. talent-granted overrides like Demonbolt).

`node_type != PASSIVE` is the castable filter `CooldownSetSpell` could not provide.
Three attempts at deriving castable-vs-aura from the Cooldown Manager tables all
failed on 2026-07-21 (see the NOTE further down); the talent tree's node_type is
the clean signal the CDM lacked. Don't retry them.

⚠ Cooldown is the load-bearing field, not the category: the layout v2 band
contract keys off ">=45s = Cooldown band". Categories are corroborating.

Each row carries:
  origin        class-baseline | talent-active | talent-choice | cdm-only
  suggestedMode fixed | float  (class-baseline/cdm-only → fixed, talent → float;
                                the seed author overrides this — see §Design)
  tree/heroTree/reqPoints        talent placement (empty for baseline/cdm-only)
  bucket        the seed bucket that binds this name today (matched BY NAME —
                DB2 uses different IDs for the same name), or None
  band          Cooldown if cooldown >= 45s else Rotational

Usage:
    uv run python -m wowkb.spec_inventory                     # summary, all specs
    uv run python -m wowkb.spec_inventory --spec Demonology   # markdown table
    uv run python -m wowkb.spec_inventory --json <path>       # dump all specs
    uv run python -m wowkb.spec_inventory --unseeded          # gap report
    uv run python -m wowkb.spec_inventory --validate Encomplete  # diff vs in-game

stdlib-only apart from the shared ROOT helper + the SavedVariables parser.
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import os
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

from ._common import ROOT
from .charstate import DEFAULT_WOW, parse_savedvar

WAGO = ROOT / "raw" / "wago"
SEED = ROOT / "projects" / "keybinder" / "data" / "bellular-keybinds.seed.json"
TALENTS = ROOT / "knowledge" / "classes" / "_talents" / "all-talents.tsv"

CATEGORY = {"0": "Essential", "1": "Utility", "2": "Buff", "3": "Other", "4": "Other"}

SPELL_ATTR0_PASSIVE = 0x40  # SpellMisc.Attributes_0 bit — a genuine passive
ACQUIRE_ARTIFACT = "3"      # SkillLineAbility.AcquireMethod for dead Legion rows

# Mirrors PLACEHOLDER in the addon's Dump.lua — bucket values that stand for a
# generated macro rather than a spell, so they never appear in game data.
PLACEHOLDER_NORM = {
    _n for _n in (
        "mount", "free", "racialability", "healthstonepotionmacro",
        "drinkingmanapotionmacro", "damagepotion", "anothercombatitemifneeded",
        "trinketmacro",
    )
}

# Universal / racial / profession spells that are castable in-game but are not
# class kit — so --validate lists them as expected, not as holes in the union.
NONCLASS_NORM = {
    _n for _n in (
        "autoattack", "shoot", "recuperate", "escapeartist", "mobilebanking",
        "revivebattlepets", "cookingfire", "basiccampfire", "chefshat",
    )
}


def _newest(stem: str) -> Path:
    """raw/wago/<stem>.csv, preferring the highest build-suffixed variant."""
    exact = WAGO / f"{stem}.csv"
    versioned = sorted(WAGO.glob(f"{stem}-*.csv"))
    if versioned:
        return versioned[-1]
    if exact.exists():
        return exact
    sys.exit(f"error: missing {stem}.csv — run: uv run python -m wowkb.wago {stem}")


def _rows(stem: str):
    with _newest(stem).open(encoding="utf-8", newline="") as fh:
        yield from csv.DictReader(fh)


def _talent_rows():
    if not TALENTS.exists():
        sys.exit(f"error: missing {TALENTS} — run: uv run python -m wowkb.talents fetch")
    with TALENTS.open(encoding="utf-8", newline="") as fh:
        yield from csv.DictReader(fh, delimiter="\t")


def _norm(name: str) -> str:
    """Loose name key so seed strings match DB2 names despite punctuation drift."""
    return re.sub(r"[^a-z0-9]+", "", (name or "").lower())


def _cooldowns() -> dict[str, float]:
    """spellID -> cooldown seconds (baseline DifficultyID 0; charge abilities carry
    the real number on the category side, so take the larger)."""
    cds: dict[str, float] = {}
    for r in _rows("SpellCooldowns"):
        if r.get("DifficultyID") != "0":
            continue
        ms = max(int(r.get("RecoveryTime") or 0), int(r.get("CategoryRecoveryTime") or 0))
        sid = r["SpellID"]
        cds[sid] = max(cds.get(sid, 0), ms / 1000.0)
    return cds


def _passive_ids() -> set[str]:
    """spellIDs flagged SPELL_ATTR0_PASSIVE — dropped from the baseline kit."""
    out = set()
    for r in _rows("SpellMisc"):
        try:
            if int(r.get("Attributes_0") or 0) & SPELL_ATTR0_PASSIVE:
                out.add(r["ID"])
        except ValueError:
            pass
    return out


def _class_skill_lines() -> dict[str, str]:
    """classID -> the SkillLine that IS that class's kit. Derived, not hardcoded:
    the class skill line is the one holding the most rows whose ClassMask is exactly
    that class's bit (Warlock classID 9 -> bit 256 -> SkillLine 849)."""
    per_line: dict[str, Counter] = defaultdict(Counter)
    for r in _rows("SkillLineAbility"):
        per_line[r["SkillLine"]][r["ClassMask"]] += 1
    out: dict[str, str] = {}
    for class_id in range(1, 14):  # 13 playable classes in 12.0.x
        bit = str(1 << (class_id - 1))
        best_line, best_n = None, 0
        for line, masks in per_line.items():
            if masks[bit] > best_n:
                best_line, best_n = line, masks[bit]
        if best_line:
            out[str(class_id)] = best_line
    return out


def _cdm_by_spec(cds: dict[str, float], names: dict[str, str]) -> dict[str, dict]:
    """spec_id -> { normname: {spellID, name, categories, order, cooldown} } from the
    Cooldown Manager tables. Annotation source AND the origin=cdm-only fallback."""
    set_to_spec = {r["ID"]: r["ChrSpecialization"] for r in _rows("CooldownSet")}
    out: dict[str, dict] = defaultdict(dict)
    for r in _rows("CooldownSetSpell"):
        spec_id = set_to_spec.get(r["CooldownSetID"])
        if not spec_id or spec_id == "0":
            continue
        sid = r["SpellID"]
        name = names.get(sid, f"<{sid}>")
        nk = _norm(name)
        rec = out[spec_id].setdefault(nk, {
            "spellID": int(sid), "name": name,
            "cooldown": round(cds.get(sid, 0.0), 1),
            "categories": set(), "order": 9999,
        })
        rec["categories"].add(CATEGORY.get(r.get("Category", ""), "Other"))
        rec["order"] = min(rec["order"], int(r.get("OrderIndex") or 0))
    return out


def _baseline_kit(cds: dict[str, float], names: dict[str, str]) -> dict[str, list[dict]]:
    """classID -> [baseline ability records]. The shared class kit the talent tree
    omits: rows on the class skill line, class-bit or all-spec (mask 0), that are
    castable (not passive) and not a dead Legion artifact row."""
    class_lines = _class_skill_lines()
    passive = _passive_ids()
    line_to_class = {line: cid for cid, line in class_lines.items()}
    out: dict[str, list[dict]] = defaultdict(list)
    seen: dict[str, set[str]] = defaultdict(set)  # classID -> normnames placed
    for r in _rows("SkillLineAbility"):
        cid = line_to_class.get(r["SkillLine"])
        if not cid:
            continue
        bit = str(1 << (int(cid) - 1))
        if r["ClassMask"] not in ("0", bit):
            continue
        if r.get("AcquireMethod") == ACQUIRE_ARTIFACT:
            continue
        sid = r["Spell"]
        if sid in passive:
            continue
        name = names.get(sid)
        if not name:  # unnamed/hidden internal spell — never player-facing
            continue
        nk = _norm(name)
        if nk in seen[cid]:
            continue
        seen[cid].add(nk)
        out[cid].append({
            "spellID": int(sid), "name": name,
            "cooldown": round(cds.get(sid, 0.0), 1),
            "origin": "class-baseline",
        })
    return out


def build() -> dict:
    names = {r["ID"]: r["Name_lang"] for r in _rows("SpellName")}
    cds = _cooldowns()

    classes = {r["ID"]: r["Name_lang"] for r in _rows("ChrClasses")}
    specs = {
        r["ID"]: {"spec": r["Name_lang"], "class": classes.get(r["ClassID"], "?"),
                  "classID": r["ClassID"]}
        for r in _rows("ChrSpecialization")
    }

    baseline = _baseline_kit(cds, names)
    cdm = _cdm_by_spec(cds, names)

    # Talent-granted actives, keyed by spec_id. node_type PASSIVE is the aura kit
    # (Soul Leech, Demonic Embrace, hero-tree throughput) — dropped; ACTIVE/CHOICE
    # are the castables. A spell can appear once per spec; key by normname so a
    # base + its choice-node twin don't both land.
    talent_inv: dict[str, dict[str, dict]] = defaultdict(dict)
    for r in _talent_rows():
        nt = r.get("node_type")
        if nt not in ("ACTIVE", "CHOICE"):
            continue
        spec_id = r.get("spec_id")
        sid = r.get("spell_id")
        name = r.get("talent")
        if not (spec_id and sid and name):
            continue
        nk = _norm(name)
        if nk in talent_inv[spec_id]:
            continue
        talent_inv[spec_id][nk] = {
            "spellID": int(sid), "name": name,
            "cooldown": round(cds.get(sid, 0.0), 1),
            "origin": "talent-choice" if nt == "CHOICE" else "talent-active",
            "tree": r.get("tree") or "",
            "heroTree": r.get("hero_tree") or "",
            "reqPoints": int(r.get("req_points") or 0),
        }

    # Cross-reference the live seed by NAME — the seed stores names, and DB2 often
    # lists a different spellID for the same name.
    seed = json.loads(SEED.read_text(encoding="utf-8"))
    seed_by_spec: dict[str, dict[str, str]] = {}
    for s in seed["specs"]:
        seed_by_spec[f"{s['class']}/{s['spec']}"] = {
            _norm(v): k for k, v in s["abilities"].items() if v
        }

    out = {}
    for spec_id, meta in specs.items():
        key = f"{meta['class']}/{meta['spec']}"
        buckets = seed_by_spec.get(key, {})

        # Union: talents ∪ class baseline ∪ cdm-only, deduped by normname with
        # origin precedence talent > baseline > cdm-only.
        merged: dict[str, dict] = {}
        for nk, rec in talent_inv.get(spec_id, {}).items():
            merged[nk] = dict(rec)
        for rec in baseline.get(meta["classID"], []):
            merged.setdefault(_norm(rec["name"]), dict(rec))
        for nk, c in cdm.get(spec_id, {}).items():
            if nk not in merged:
                merged[nk] = {
                    "spellID": c["spellID"], "name": c["name"],
                    "cooldown": c["cooldown"], "origin": "cdm-only",
                }

        rows = []
        for nk, rec in merged.items():
            rec.setdefault("tree", "")
            rec.setdefault("heroTree", "")
            rec.setdefault("reqPoints", 0)
            ann = cdm.get(spec_id, {}).get(nk)
            rec["categories"] = sorted(ann["categories"]) if ann else []
            rec["order"] = ann["order"] if ann else 9999
            rec["bucket"] = buckets.get(nk)
            rec["band"] = "Cooldown" if rec["cooldown"] >= 45 else "Rotational"
            rec["suggestedMode"] = "float" if rec["origin"].startswith("talent") else "fixed"
            # node_type != PASSIVE is the primary castable filter, but a CHOICE node
            # is often passive-vs-passive (hero-tree throughput, curse/Healthstone/
            # Grimoire modifiers) — those carry no cooldown, no CDM tracking entry
            # and no seed binding, whereas every real active choice (Implosion/Power
            # Siphon, the Grimoire pair, Shadowfury/Howl of Terror) has at least one.
            # The passive-attribute bit does NOT catch these (verified 2026-07-21:
            # Infernal Vitality, Mark of Shatug et al. have attr0 without 0x40), so
            # this three-signal test is the only clean discriminator. ACTIVE nodes
            # are always kept — Blizzard reserves ACTIVE for grants that add a button.
            if (rec["origin"] == "talent-choice" and rec["cooldown"] == 0
                    and not rec["categories"] and not rec["bucket"]):
                continue
            # NOTE: no castable-vs-aura flag is derived from the Cooldown Manager
            # tables. node_type from the talent tree IS the castable filter the CDM
            # lacked; cdm-only rows are the residue (may include auras like Demonic
            # Core — labelled cdm-only so the consumer treats them with suspicion).
            # The three failed CDM discriminators (2026-07-21): Buff-category+no-CD
            # flags Soulburn/Banish/Fear; has-a-SpellCooldowns-row misses Fear/
            # Soulburn; SPELL_ATTR0_PASSIVE catches only Diabolic Ritual.
            rows.append(rec)
        rows.sort(key=lambda r: (r["order"], -r["cooldown"], r["name"]))

        inv_names = {_norm(r["name"]) for r in rows}
        orphans = sorted(
            b for n, b in buckets.items()
            if n not in inv_names and n not in PLACEHOLDER_NORM
        )
        if spec_id not in talent_inv:
            continue  # not a real player spec: hunter-pet specs (Cunning/Ferocity/
                      # Tenacity), Adventurer, and each class's "Initial" no-spec
                      # state — none has a talent tree (only baseline kit leaks in)
        out[key] = {
            "specID": int(spec_id),
            "class": meta["class"],
            "spec": meta["spec"],
            "abilities": rows,
            "seedOrphans": orphans,
        }
    return dict(sorted(out.items()))


def _table(entry: dict) -> str:
    lines = [
        f"## {entry['class']} — {entry['spec']}  (specID {entry['specID']}, "
        f"{len(entry['abilities'])} abilities)",
        "",
        "| # | Ability | ID | CD | Origin | Mode | Band | Blizz cat | Seed bucket |",
        "|---|---|---|---:|---|---|---|---|---|",
    ]
    for i, a in enumerate(entry["abilities"], 1):
        cd = f"{a['cooldown']:g}s" if a["cooldown"] else "—"
        tree = f" {a['heroTree']}" if a.get("heroTree") else ""
        lines.append(
            f"| {i} | {a['name']}{tree} | `{a['spellID']}` | {cd} | "
            f"{a['origin']} | {a['suggestedMode']} | {a['band']} | "
            f"{'/'.join(a['categories']) or '—'} | {a['bucket'] or '**—**'} |"
        )
    if entry["seedOrphans"]:
        lines += ["", "**Seed buckets with no inventory match** (stale name, placeholder, "
                  "or untracked): " + ", ".join(f"`{b}`" for b in entry["seedOrphans"])]
    return "\n".join(lines)


def _aslist(v) -> list:
    if isinstance(v, list):
        return v
    if isinstance(v, dict):
        return [v[k] for k in sorted(v)] if v else []
    return []


def _validate(data: dict, character: str, wow_path: str) -> int:
    """Diff the computed inventory against a real in-game /bb diagnostics dump.

    Reports false-negatives (castable in game, missing from our union — the holes
    that matter) and false-positives (marked class-baseline by us but not castable
    in game — a wrong baseline classification)."""
    pattern = f"{wow_path}/WTF/Account/*/SavedVariables/BucketBinds.lua"
    hits = sorted(glob.glob(pattern), key=os.path.getmtime, reverse=True)
    if not hits:
        print(f"No BucketBinds.lua under {pattern}.", file=sys.stderr)
        print("Run /bb diagnostics in-game and /reload first.", file=sys.stderr)
        return 1
    db = parse_savedvar(Path(hits[0]).read_text(encoding="utf-8", errors="replace"),
                        "BucketBindsDB")
    tree = (db or {}).get("diagnostics")
    if not isinstance(tree, dict) or not tree:
        print(f"No diagnostics recorded in {hits[0]}.", file=sys.stderr)
        return 1

    matched = 0
    for char in sorted(tree):
        if character.lower() not in char.lower():
            continue
        byspec = tree[char]
        if not isinstance(byspec, dict):
            continue
        for specName, report in sorted(byspec.items()):
            if not isinstance(report, dict):
                continue
            classDisplay = (report.get("meta") or {}).get("classDisplay")
            key = f"{classDisplay}/{specName}"
            entry = data.get(key)
            print(f"\n── validate {char} / {specName}  (inventory key: {key}) ──")
            if not entry:
                print(f"   no computed inventory for {key!r} — cannot diff.")
                continue
            matched += 1

            # In-game castable = resolved-known buckets + unmapped gaps. (untalented
            # / unresolved / placeholder are NOT castable.) Keyed by norm-name AND
            # normID so an override or a name drift still matches.
            game_names, game_ids = set(), set()
            game_list = []  # (name, id)
            for b in _aslist(report.get("buckets")):
                if b.get("class") == "resolved-known":
                    game_names.add(_norm(b.get("name", "")))
                    if b.get("normID"):
                        game_ids.add(int(b["normID"]))
                    game_list.append((b.get("name"), b.get("normID") or b.get("spellID")))
            for u in _aslist(report.get("unmapped")):
                game_names.add(_norm(u.get("name", "")))
                if u.get("id"):
                    game_ids.add(int(u["id"]))
                game_list.append((u.get("name"), u.get("id")))

            inv_names = {_norm(a["name"]) for a in entry["abilities"]}
            inv_ids = {a["spellID"] for a in entry["abilities"]}

            false_neg, noncls = [], []
            for nm, sid in game_list:
                nk = _norm(nm or "")
                if nk in inv_names or (sid and int(sid) in inv_ids):
                    continue
                (noncls if nk in NONCLASS_NORM else false_neg).append((nm, sid))

            false_pos = [
                a for a in entry["abilities"]
                if a["origin"] == "class-baseline"
                and _norm(a["name"]) not in game_names
                and a["spellID"] not in game_ids
            ]

            print(f"   in-game castable: {len(game_list)}  ·  computed inventory: "
                  f"{len(entry['abilities'])}")
            if false_neg:
                print(f"   ✗ FALSE NEGATIVES — castable in game, MISSING from the union "
                      f"({len(false_neg)}):")
                for nm, sid in sorted(false_neg):
                    print(f"       {nm} ({sid})")
            else:
                print("   ✓ no false negatives (every in-game class ability is in the union)")
            if noncls:
                print(f"   · non-class castables (racial/profession/universal — expected, "
                      f"{len(noncls)}): " + ", ".join(f"{n}" for n, _ in sorted(noncls)))
            if false_pos:
                print(f"   ! FALSE POSITIVES — marked class-baseline but not castable in "
                      f"game ({len(false_pos)}):")
                for a in sorted(false_pos, key=lambda a: a["name"]):
                    print(f"       {a['name']} ({a['spellID']})")

    if matched == 0:
        print(f"\nNo diagnostics report matched character {character!r}.")
        return 1
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--spec", help="render one spec as a markdown table (spec name or Class/Spec)")
    ap.add_argument("--json", metavar="PATH", help="write the full inventory as JSON")
    ap.add_argument("--unseeded", action="store_true",
                    help="list, per spec, the abilities no seed bucket covers")
    ap.add_argument("--validate", metavar="CHARACTER",
                    help="diff the union against a real in-game /bb diagnostics dump")
    ap.add_argument("--wow-path", default=DEFAULT_WOW,
                    help=f"WoW _retail_ path for --validate (default: {DEFAULT_WOW})")
    args = ap.parse_args()

    data = build()

    if args.validate:
        return _validate(data, args.validate, args.wow_path)

    if args.json:
        Path(args.json).write_text(json.dumps(data, indent=2), encoding="utf-8")
        print(f"wrote {args.json}  ({len(data)} specs, "
              f"{sum(len(v['abilities']) for v in data.values())} ability rows)")
        return 0

    if args.spec:
        want = args.spec.lower()
        hits = [k for k in data if want in k.lower()]
        if not hits:
            sys.exit(f"no spec matches '{args.spec}'. Known: {', '.join(sorted(data))}")
        for k in hits:
            print(_table(data[k]), end="\n\n")
        return 0

    if args.unseeded:
        for k, v in data.items():
            miss = [a for a in v["abilities"] if not a["bucket"]]
            print(f"{k:<34}{len(miss):>3} unbound / {len(v['abilities']):>3}")
            for a in sorted(miss, key=lambda a: -a["cooldown"])[:6]:
                cd = f"{a['cooldown']:g}s" if a["cooldown"] else "—"
                print(f"     {a['name']:<34}{cd:>7}  {a['origin']}")
        return 0

    tot = sum(len(v["abilities"]) for v in data.values())
    unb = sum(1 for v in data.values() for a in v["abilities"] if not a["bucket"])
    print(f"{len(data)} specs, {tot} ability rows, {unb} with no seed bucket "
          f"({unb * 100 // max(tot, 1)}%)")
    for k, v in data.items():
        miss = sum(1 for a in v["abilities"] if not a["bucket"])
        floats = sum(1 for a in v["abilities"] if a["suggestedMode"] == "float")
        print(f"  {k:<34}{len(v['abilities']):>4} abilities  {miss:>3} unbound"
              f"  {floats:>3} float  {len(v['seedOrphans']):>2} orphans")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
