#!/usr/bin/env python3
"""Extract the Bellular "Midnight Keybind Planner" workbook into the canonical
seed the addon consumes.

Emits two artifacts from one source spreadsheet:
  * data/bellular-keybinds.seed.json  -- canonical, human-diffable
  * addon/BucketBinds/Data.lua        -- generated Lua table the addon loads

The workbook is a snapshot (lives on the Windows host + Google Sheets) and will
rot as Blizzard prunes/adds spells. This script is the reproducible bridge:
refresh the .xlsx, re-run, diff the JSON.

Usage:
    uv run --with openpyxl python extract_seed.py [path-to.xlsx]

Default source path is the WSL view of the user's Downloads folder.
"""
import json
import sys
from pathlib import Path

import openpyxl

DEFAULT_XLSX = (
    "/mnt/c/Users/mchris/Downloads/"
    "Copy of Midnight Keybind Planner (Oldschool Edition).xlsx"
)
HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent
JSON_OUT = PROJECT / "data" / "bellular-keybinds.seed.json"
LUA_OUT = PROJECT / "addon" / "BucketBinds" / "Data.lua"

# class tabs, in the workbook's tab order
CLASS_TABS = [
    "Death Knight", "Paladin", "Warrior", "Evoker", "Hunter", "Shaman",
    "Demon Hunter", "Druid", "Monk", "Rogue", "Mage", "Priest", "Warlock",
]


def cell(v):
    """Normalize a cell value to a trimmed string (ints stay int-like)."""
    if v is None:
        return None
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    return str(v).strip() or None


def extract(xlsx_path):
    wb = openpyxl.load_workbook(xlsx_path, data_only=True)

    # 1. bucket -> default keybind (+ the out-of-combat "bonus" binds)
    ws = wb["ENTER YOUR BINDS HERE"]
    buckets, bonus = [], []
    for r in range(3, ws.max_row + 1):
        cat, key = cell(ws.cell(r, 1).value), cell(ws.cell(r, 2).value)
        if cat:
            buckets.append({"category": cat, "keybind": key})
        bcat, bkey = cell(ws.cell(r, 3).value), cell(ws.cell(r, 4).value)
        if bcat:
            bonus.append({"category": bcat, "keybind": bkey})

    # bar/slot per category, from the Master Sheet
    ws = wb["Master Sheet"]
    barslot = {}
    for r in range(2, ws.max_row + 1):
        cat = cell(ws.cell(r, 4).value)
        if cat:
            barslot[cat] = (cell(ws.cell(r, 1).value), cell(ws.cell(r, 2).value))
    for b in buckets:
        bs = barslot.get(b["category"])
        if bs:
            b["bar"], b["slot"] = bs

    # 2. per-spec ability map, read from each class tab (authoritative headers)
    specs = []
    for cl in CLASS_TABS:
        ws = wb[cl]
        spec_cols = []
        for c in range(3, ws.max_column + 1):
            h = cell(ws.cell(1, c).value)
            if h in (None, "Notes", "Legend"):
                break
            spec_cols.append((c, h))
        for c, spec in spec_cols:
            abilities = {}
            for r in range(2, ws.max_row + 1):
                cat, a = cell(ws.cell(r, 1).value), cell(ws.cell(r, c).value)
                if cat and a:
                    abilities[cat] = a
            specs.append({"class": cl, "spec": spec, "abilities": abilities})

    # 3. reference tables
    def table(name):
        ws = wb[name]
        hdr = [cell(ws.cell(1, c).value) for c in range(1, ws.max_column + 1)]
        rows = []
        for r in range(2, ws.max_row + 1):
            row = {
                hdr[c - 1]: cell(ws.cell(r, c).value)
                for c in range(1, ws.max_column + 1)
                if hdr[c - 1]
            }
            if any(row.values()):
                rows.append(row)
        return rows

    return {
        "source": "Bellular Midnight Keybind Planner (Oldschool Edition) — user copy",
        "notation": {
            "digits": "number row (1-4)", "letters": "Q E R F etc",
            "S<key>": "Shift+key", "C<key>": "Ctrl+key", "A<key>": "Alt+key",
            "F1-F4": "stance/form bars",
        },
        "buckets": buckets,
        "bonus_binds": bonus,
        "specs": specs,
        "items": table("Items"),
        "buffs": table("Buffs"),
    }


def to_lua(data):
    """Render the seed as a Lua module assigned into the addon namespace."""
    def q(s):
        return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'

    lines = [
        "-- GENERATED by tool/extract_seed.py — do not edit by hand.",
        "-- Source: " + data["source"],
        "local _, ns = ...",
        "ns.SEED = {",
        "  buckets = {",
    ]
    for b in data["buckets"]:
        parts = [f"category={q(b['category'])}", f"keybind={q(b.get('keybind'))}"]
        if b.get("bar"):
            parts.append(f"bar={b['bar']}")
        if b.get("slot"):
            parts.append(f"slot={b['slot']}")
        lines.append("    {" + ", ".join(parts) + "},")
    lines.append("  },")
    lines.append("  specs = {")
    for s in data["specs"]:
        lines.append(f"    [{q(s['class'] + '/' + s['spec'])}] = {{")
        for cat, ab in s["abilities"].items():
            lines.append(f"      [{q(cat)}] = {q(ab)},")
        lines.append("    },")
    lines.append("  },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    xlsx = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(DEFAULT_XLSX)
    if not xlsx.exists():
        sys.exit(f"source workbook not found: {xlsx}")
    data = extract(xlsx)
    JSON_OUT.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    LUA_OUT.write_text(to_lua(data))
    n_ab = sum(len(s["abilities"]) for s in data["specs"])
    print(f"wrote {JSON_OUT.relative_to(PROJECT)}")
    print(f"wrote {LUA_OUT.relative_to(PROJECT)}")
    print(
        f"  buckets={len(data['buckets'])} specs={len(data['specs'])} "
        f"abilities={n_ab} items={len(data['items'])} buffs={len(data['buffs'])}"
    )


if __name__ == "__main__":
    main()
