#!/usr/bin/env python3
"""Generate the addon's Data.lua from the canonical seed JSON.

    data/bellular-keybinds.seed.json  (canonical, hand-editable source of truth)
        └─ gen_data_lua.py → addon/BucketBinds/Data.lua  (generated build artifact)

This is the ONE step in the live workflow. The Bellular .xlsx is now a frozen
archive (see extract_seed.py) and is NOT part of routine maintenance — edit the
JSON directly and re-run this. `Data.lua` is generated; never hand-edit it.

Usage:
    uv run python tool/gen_data_lua.py        # or plain: python3 tool/gen_data_lua.py
    python3 tool/gen_data_lua.py --check      # verify Data.lua is in sync (CI); nonzero if not
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent
JSON_IN = PROJECT / "data" / "bellular-keybinds.seed.json"
LUA_OUT = PROJECT / "addon" / "BucketBinds" / "Data.lua"

# Bellular's `buffs` sheet uses fuzzy `Spec` strings — a bare class display name
# ("Mage"), a "<Class> (Sans Resto)" exclusion, or a "<Qualifier> <Class>" prefix
# ("Enhancement Shaman", "Resto Shaman"). We resolve these to real seed specs once
# in Python (auditable) rather than at runtime in Lua. `Flasks` is a spreadsheet
# artifact (mis-zipped catalog) and is ignored.


def _buff_applies(specstr, class_name, spec_name):
    """Does a buff row's `Spec` string apply to this class/spec? (case-insensitive)"""
    s = specstr.strip().lower()
    cn = class_name.strip().lower()
    sn = spec_name.strip().lower()
    sans = "(sans resto)"
    if s.endswith(sans):
        base = s[: -len(sans)].strip()
        return base == cn and sn != "restoration"
    if s == cn:
        return True
    # "<qualifier> <class>" → qualifier must be a prefix of the spec name
    # ("Resto" ⊂ "Restoration", "Enhancement" ⊂ "Enhancement").
    if s.endswith(" " + cn):
        qual = s[: -len(cn)].strip()
        return bool(qual) and sn.startswith(qual)
    return False


def _buff_spell(row):
    """The castable spell for a buff row. `Poisons Macro` is a placeholder for the
    Rogue's real lethal poison; every other row's `Buff` is already a spell."""
    if row["Buff"].strip().lower() == "poisons macro":
        return "Instant Poison"  # @verify-ingame (poison names in 12.0.7)
    return row["Buff"]


def _spec_buffs(data):
    """Map each seed spec key ("Mage/Frost") → ordered buff spell list (buff-sheet
    order). Only specs with ≥1 matching buff are included."""
    out = {}
    for s in data["specs"]:
        names = [
            _buff_spell(b)
            for b in data.get("buffs", [])
            if _buff_applies(b["Spec"], s["class"], s["spec"])
        ]
        if names:
            out[s["class"] + "/" + s["spec"]] = names
    return out


def _item_groups(data):
    """Partition the flat `items` list into ordered groups. A row with both IDs
    null is a header naming the next group; each real row → (q2, q1) int pair."""
    groups, order, current = {}, [], None
    for row in data.get("items", []):
        if row.get("Q2 ID") is None and row.get("Q1 ID") is None:
            current = row["Type"]
            groups[current] = []
            order.append(current)
        elif current is not None:
            groups[current].append((int(row["Q2 ID"]), int(row["Q1 ID"])))
    return order, groups


def to_lua(data):
    """Render the seed as a Lua module assigned into the addon namespace."""
    def q(s):
        return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'

    lines = [
        "-- GENERATED by tool/gen_data_lua.py from data/bellular-keybinds.seed.json",
        "-- Do not edit by hand — edit the seed JSON and regenerate.",
        "-- Source: " + data.get("source", "bellular-keybinds.seed.json"),
        "local _, ns = ...",
        "ns.SEED = {",
        "  buckets = {",
    ]
    for b in data["buckets"]:
        parts = [f"category={q(b['category'])}", f"keybind={q(b.get('keybind'))}"]
        if b.get("bar"):
            parts.append(f"bar={b['bar']}")
        if b.get("slot"):
            parts.append(f"slot={b['slot']}")
        lines.append("    {" + ", ".join(parts) + "},")
    lines.append("  },")
    lines.append("  specs = {")
    for s in data["specs"]:
        lines.append(f"    [{q(s['class'] + '/' + s['spec'])}] = {{")
        for cat, ab in s["abilities"].items():
            lines.append(f"      [{q(cat)}] = {q(ab)},")
        lines.append("    },")
    lines.append("  },")
    # excludeSpells: a set keyed by spellID (numeric) and/or name (string) that
    # Dump.Spill and Dump.Ring suppress (auto-attack, wand, battle-pet mgmt, …).
    # Edit the seed's `exclude_spells` list, not this generated table.
    lines.append("  excludeSpells = {")
    for e in data.get("exclude_spells", []):
        if e.get("id"):
            note = (" -- " + e["name"]) if e.get("name") else ""
            lines.append(f"    [{int(e['id'])}] = true,{note}")
        elif e.get("name"):
            lines.append(f"    [{q(e['name'])}] = true,")
    lines.append("  },")
    # items: grouped consumables (Health/Mana/Damage/Flasks/Oils). Each group is
    # an ordered list of {q2, q1} ID pairs (q2 = higher rank first). Macros.lua's
    # fall-through builders /use every ID so whichever the player carries fires.
    order, groups = _item_groups(data)
    lines.append("  items = {")
    for name in order:
        pairs = ", ".join(f"{{{q2}, {q1}}}" for q2, q1 in groups[name])
        lines.append(f"    {name} = {{ {pairs} }},")
    lines.append("  },")
    # specBuffs: per-spec pre-pull buff spell list, pre-resolved from `buffs`.
    lines.append("  specBuffs = {")
    for key, names in _spec_buffs(data).items():
        buffs = ", ".join(q(n) for n in names)
        lines.append(f"    [{q(key)}] = {{ {buffs} }},")
    lines.append("  },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    if not JSON_IN.exists():
        sys.exit(f"seed not found: {JSON_IN}")
    data = json.loads(JSON_IN.read_text())
    lua = to_lua(data)

    if "--check" in sys.argv[1:]:
        current = LUA_OUT.read_text() if LUA_OUT.exists() else ""
        if current != lua:
            sys.exit(
                f"Data.lua is OUT OF SYNC with {JSON_IN.name}. "
                f"Run: python3 tool/gen_data_lua.py"
            )
        print("Data.lua in sync with seed JSON.")
        return

    LUA_OUT.write_text(lua)
    n_ab = sum(len(s["abilities"]) for s in data["specs"])
    n_placed = sum(1 for b in data["buckets"] if b.get("bar"))
    print(f"wrote {LUA_OUT.relative_to(PROJECT)}")
    print(
        f"  buckets={len(data['buckets'])} ({n_placed} placed) "
        f"specs={len(data['specs'])} abilities={n_ab}"
    )


if __name__ == "__main__":
    main()
